version: "3.7"

services:
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sns,sqs
      DEFAULT_REGION: eu-west-1
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    volumes:
      - ${PWD}/localstack/initscripts:/docker-entrypoint-initaws.d
      - ${HOME}/.aws:/root/.aws

  spikeyapp:
    image: maven:3-amazoncorretto-11
    working_dir: /usr/src/mymaven
    command: mvn spring-boot:run
    volumes:
      - ${PWD}:/usr/src/mymaven
      - ${HOME}/.m2:/root/.m2
      - ${HOME}/.aws:/root/.aws
    ports:
      - "30000:8080"
    environment:
      AWS_PROFILE: local
